---
- name: Make sure that the karabiner config folder is created
  loop:
    - karabiner
    - karabiner/assets
    - karabiner/assets/complex_modifications
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
    owner: "{{ username }}"
    mode: "0755"

- name: Deploy the karabiner asset files
  with_fileglob: "files/assets/complex_modifications/*.json"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/karabiner/assets/complex_modifications/{{ item | basename }}"
    state: link

- name: Deploy the karabiner asset files
  ansible.builtin.file:
    src: "{{ role_path }}/files/karabiner.json"
    dest: "{{ ansible_env.HOME }}/.config/karabiner/karabiner.json"
    state: link
