---
system:
  packages:
    brew:
      - neovim
      - figlet
      - yarn
      - nodejs
      - fish
      - neofetch
      - tmux
      - bitwarden-cli
    cask:
      - kitty
      - karabiner-elements
