---
- name: Download the larry3d font (for startify splash screen)
  become: yes
  become_user: "{{ brew_user }}"
  ansible.builtin.get_url:
    url: https://github.com/xero/figlet-fonts/raw/master/larry3d.flf
    dest: "{{ nvim.prefix.figlet }}/larry3d.flf"
    mode: 0644

- name: Create the nvim configuration folders
  loop:
    - nvim/
    - nvim/after
    - nvim/after/plugin
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
    owner: "{{ username }}"
    mode: "0755"

- name: Deploy the nvim configuration files
  with_fileglob:
    - "files/*.vim"
    - "files/*.json"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/{{ item | basename }}"
    state: link

- name: Deploy the nvim plugin configuration files
  with_fileglob:
    - "files/after/plugin/*.vim"
    - "files/after/plugin/*.lua"
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim//after/plugin/{{ item | basename }}"
    state: link

- name: Check if vim-plug is installed
  register: nvim_vim_plug
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"

- name: Create the vim-plug folders
  loop:
    - ".local"
    - ".local/share"
    - ".local/share/nvim"
    - ".local/share/nvim/site"
    - ".local/share/nvim/site/autoload"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    owner: "{{ username }}"
    state: directory
    mode: "0755"

- name: Download and install vim-plug
  when: not nvim_vim_plug.stat.exists
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/autoload/plug.vim"
    owner: "{{ username }}"
    mode: "0644"

- name: Install and update nvim plugins
  changed_when: no
  ansible.builtin.command:
    cmd: nvim -c "PlugInstall" -c "PlugUprade" -c "PlugUpdate" -c "qa"
